"""initial from 11/14 sql dump

Revision ID: 13ebf4f9ef6d
Revises: None
Create Date: 2015-09-27 20:06:34.344000

"""

# revision identifiers, used by Alembic.
revision = '13ebf4f9ef6d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
