"""changing models.User to models.Person

Revision ID: 30d0670988eb
Revises: 13ebf4f9ef6d
Create Date: 2015-09-27 21:21:35.522000

"""

# revision identifiers, used by Alembic.
revision = '30d0670988eb'
down_revision = '13ebf4f9ef6d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forum_category',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('person',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('permission_level', sa.Integer(), nullable=True),
    sa.Column('avatar', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('forum_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=256), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('author', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['person.username'], ),
    sa.ForeignKeyConstraint(['category'], ['forum_category.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forum_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('topic', sa.Integer(), nullable=True),
    sa.Column('author', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['person.username'], ),
    sa.ForeignKeyConstraint(['topic'], ['forum_topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forum_post')
    op.drop_table('forum_topic')
    op.drop_table('person')
    op.drop_table('forum_category')
    op.drop_table('file')
    ### end Alembic commands ###
